package com.example.signupservice.domain.error;

public enum ErrorCode {
    EMAIL_REQUIRED,
    PASSWORD_REQUIRED,
    EMAIL_INVALID,
    PASSWORD_TOO_SHORT,
    PASSWORD_TOO_LONG,
    EMAIL_TAKEN,
    INVALID_CREDENTIALS,
    IDEMPOTENCY_KEY_REQUIRED,
    IDEMPOTENCY_KEY_INVALID,
    IDEMPOTENCY_KEY_BODY_MISMATCH,
    INTERNAL
}
